// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfyfgqsdotxfzwjxzddw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmeWZncXNkb3R4Znp3anh6ZGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMTEyMDksImV4cCI6MjA2NzY4NzIwOX0.VofSd6--xTLNSLee1bFcBZPfODhF3DAP5JwRIpVMJ_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});